# This file is generated by /usr/bin/pypi2portage automatically.

inherit distutils

MY_PF=sphinx-intl-0.9.5.tar.gz
MY_PD=sphinx-intl-0.9.5

DESCRIPTION="Sphinx utility that make it easy to translate and to apply translation."
HOMEPAGE="https://bitbucket.org/shimizukawa/sphinx-intl"
#SRC_URI="http://what/${MY_PF}"
SRC_URI="https://pypi.python.org/packages/source/s/sphinx-intl/sphinx-intl-0.9.5.tar.gz"
LICENSE="BSD"
KEYWORDS="~alpha ~amd64 ~hppa ~ia64 ~ppc ~ppc64 ~sparc ~x86"
SLOT="0"
IUSE="doc test transifex"

RDEPEND="dev-python/setuptools
	dev-python/six
	dev-python/polib
	dev-python/sphinx"
DEPEND="${RDEPEND}
	dev-python/setuptools
	doc? ( dev-python/pudge dev-python/buildutils )
	test? ( dev-python/nose )
	transifex? ( dev-python/transifex_client )"

S=${WORKDIR}/${MY_PD}

src_unpack() {
	distutils_src_unpack
	
	if [ -f fixsetup.py ]; then
		einfo 'Run fixsetup.py'
		${python} fixsetup.py
	fi
}

src_compile() {
	distutils_src_compile
	if use doc ; then
		PYTHONPATH=. "${python}" setup.py pudge || die "generating doc failed."
	fi
}

src_install() {
	distutils_src_install
	use doc && dohtml -r docs/html/*
}
